export const MEDICATION_SUGGESTIONS = [
  "Paracetamol",
  "Dolo 650",
  "Crocin",
  "Calpol",
  "Combiflam",
  "Ibuprofen",
  "Aceclofenac",
  "Diclofenac",
  "Meftal Spas",
  "Zerodol",
  "Tramadol",
  "Aspirin",
  "Disprin",
  "Ecosprin",

  // Fever / Cold / Cough
  "Cetirizine",
  "Levocetirizine",
  "Fexofenadine",
  "Allegra",
  "Benadryl",
  "Corex",
  "Ascoril",
  "Alex Syrup",
  "TusQ",
  "Ambroxol",
  "Sinarest",
  "Wikoryl",
  "Vicks Action 500",
  "Cofsils",
  "Strepsils",

  // Antibiotics
  "Amoxicillin",
  "Augmentin",
  "Azithromycin",
  "Azee 500",
  "Ciprofloxacin",
  "Ofloxacin",
  "Levofloxacin",
  "Cefixime",
  "Monocef",
  "Taxim O",
  "Zifi 200",
  "Doxycycline",
  "Clarithromycin",
  "Moxikind CV",

  // Stomach / Acidity
  "Pantoprazole",
  "Pantocid",
  "Omeprazole",
  "Omez",
  "Rablet",
  "Pan D",
  "Digene",
  "Gelusil",
  "ENO",
  "Rantac",
  "Domperidone",
  "Ondansetron",
  "Cyclopam",
  "Buscopan",

  // Diarrhea / Vomiting
  "ORS",
  "Electral",
  "Loperamide",
  "Eldoper",
  "Flagyl",
  "Metrogyl",
  "Tiniba",
  "Norflox TZ",

  // Diabetes
  "Metformin",
  "Glycomet",
  "Glimepiride",
  "Glimiprex",
  "Vildagliptin",
  "Januvia",
  "Insulin Glargine",
  "Insulin Aspart",
  "Human Mixtard",

  // Blood Pressure / Heart
  "Amlodipine",
  "Telma",
  "Telmisartan",
  "Olmesartan",
  "Losartan",
  "Lisinopril",
  "Ramipril",
  "Atenolol",
  "Metoprolol",
  "Carvedilol",
  "Propranolol",
  "Clopidogrel",
  "Warfarin",

  // Cholesterol
  "Atorvastatin",
  "Rosuvastatin",
  "Simvastatin",
  "Fenofibrate",

  // Vitamins / Supplements
  "Vitamin D3",
  "Shelcal",
  "Limcee",
  "Becosules",
  "Neurobion Forte",
  "Evion 400",
  "Supradyn",
  "Revital",
  "Zincovit",
  "Ferrous Sulphate",

  // Asthma / Breathing
  "Asthalin",
  "Salbutamol",
  "Budecort",
  "Foracort",
  "Duolin",
  "Montelukast",
  "Deriphyllin",

  // Skin / Creams
  "Betadine",
  "Soframycin",
  "Candid Cream",
  "Clotrimazole",
  "Panderm",
  "Mupirocin",
  "Calamine Lotion",

  // Pain Relief Sprays / Gels
  "Volini",
  "Moov",
  "Iodex",

  // Thyroid
  "Thyronorm",
  "Eltroxin",
  "Levothyroxine",

  // Mental Health / Sleep
  "Alprazolam",
  "Clonazepam",
  "Escitalopram",
  "Fluoxetine",
  "Sertraline",
  "Paroxetine",
  "Amitriptyline",
  "Zolpidem",

  // General Common Medicines
  "Liv 52",
  "Ursocol",
  "Duphalac",
  "Cremaffin",
  "Albendazole",
  "Ivermectin",
  "Hydroxychloroquine",
  "Oseltamivir",
  "Remdesivir",
  "Nitrofurantoin",
  "Pregabalin",
  "Gabapentin",
  "Tamsulosin",
  "Wysolone",
  "Dexona",
  "Betnesol"
];